[project]
name = "ai-full-stack-developer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "jedi>=0.19.2",
    "llama-index>=0.14.5",
    "llama-index-llms-openai>=0.6.5",
    "llama-index-llms-perplexity>=0.4.2",
]
